name: commit
on: [push]
jobs:
  test-prolog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y swi-prolog
      - run: python3 -c "import build ; build.test_prolog()"    
  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - test-prolog
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ${XDG_RUNTIME_DIR}/containers/
      - env:
          QUAY_IO_DOCKER_CONFIG: ${{ secrets.QUAY_IO_DOCKER_CONFIG }}
        run: echo "${QUAY_IO_DOCKER_CONFIG}" >${XDG_RUNTIME_DIR}/containers/auth.json
      - run: python3 -c "import build ; build.build_images_and_push()"
